# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeLimits < Formula
  desc "CLI tool to check Claude.ai usage limits for Pro/Max subscriptions"
  homepage "https://github.com/benjaminabbitt/claude-limits"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.1.1/claude-limits_0.1.1_darwin_amd64.tar.gz"
      sha256 "19253fddde29703f7dacac2afe68d7b386bfb5022dd95c01c3c1325ba4e4ef90"

      def install
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.1.1/claude-limits_0.1.1_darwin_arm64.tar.gz"
      sha256 "8c55c4bbeed866db9ae8a199f53af0beaba836d4e81746dc13da4d34dac384f0"

      def install
        bin.install "claude-limits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.1.1/claude-limits_0.1.1_linux_amd64.tar.gz"
      sha256 "8a509124f4a9ea59d4449a4ff54e63d3b0cfcbf2dfbbeda86cfd6d6b06f895e3"
      def install
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.1.1/claude-limits_0.1.1_linux_arm64.tar.gz"
      sha256 "8a8245fce4134a77db2847fd53cdf2024b97933e94a543b3414ea521e0116df9"
      def install
        bin.install "claude-limits"
      end
    end
  end

  test do
    system "#{bin}/claude-limits", "--help"
  end
end
