# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeLimits < Formula
  desc "CLI tool to check Claude.ai usage limits for Pro/Max subscriptions"
  homepage "https://github.com/benjaminabbitt/claude-limits"
  version "0.1.0-0-20251229033220-6f84372"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.1.0-0-20251229033220-6f84372/claude-limits_0.1.0-0-20251229033220-6f84372_darwin_amd64.tar.gz"
      sha256 "92eccd26ad48813270b6dceb7575ba84ff4ace026bc908a49dec9df58bcd9b58"

      def install
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.1.0-0-20251229033220-6f84372/claude-limits_0.1.0-0-20251229033220-6f84372_darwin_arm64.tar.gz"
      sha256 "3ad9b337171768e3ea9ac833ad7e49aee72b0b0ccf47099735408ed5a6df61ac"

      def install
        bin.install "claude-limits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.1.0-0-20251229033220-6f84372/claude-limits_0.1.0-0-20251229033220-6f84372_linux_amd64.tar.gz"
      sha256 "6459d295ed0a458d8ae29d8a96861426fbe0f4a30598325a4bf9cda291213700"
      def install
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.1.0-0-20251229033220-6f84372/claude-limits_0.1.0-0-20251229033220-6f84372_linux_arm64.tar.gz"
      sha256 "13c81392289ce680dfc76900bc97a745d7a717c9e9d2886e856d241655e9840c"
      def install
        bin.install "claude-limits"
      end
    end
  end

  test do
    system "#{bin}/claude-limits", "--help"
  end
end
