# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClaudeLimits < Formula
  desc "CLI tool to check Claude.ai usage limits for Pro/Max subscriptions"
  homepage "https://github.com/benjaminabbitt/claude-limits"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.2.0/claude-limits_0.2.0_darwin_amd64.tar.gz"
      sha256 "4a4adf7db1c88d8d97c77c7cca76feb89e646b7021395b1e54bfe190452b5e76"

      def install
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.2.0/claude-limits_0.2.0_darwin_arm64.tar.gz"
      sha256 "18146d06a8d30667476ca46a2411a7ec223a5839222cf49043f178682eb7ab3a"

      def install
        bin.install "claude-limits"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.2.0/claude-limits_0.2.0_linux_amd64.tar.gz"
      sha256 "98a65b5342247f61788fda15265bf3afa1a2c37b766708cf62a48e32d62c7d94"
      def install
        bin.install "claude-limits"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminabbitt/claude-limits/releases/download/v0.2.0/claude-limits_0.2.0_linux_arm64.tar.gz"
      sha256 "b51710e7333f7733be4a12d95527e0021c3e4f5962a30d6ee2e252a8043e5a85"
      def install
        bin.install "claude-limits"
      end
    end
  end

  test do
    system "#{bin}/claude-limits", "--help"
  end
end
